name: Auto Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Get diff
        id: get_diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD > pr.diff
          echo "::set-output name=diff::$(cat pr.diff | base64 -w 0)"

      - name: Call GPT for review
        id: gpt_review
        uses: actions/github-script@v6
        with:
          script: |
            const diff = Buffer.from(process.env.DIFF, 'base64').toString('utf8');
            // 你可以用 OpenAI API 來分析 diff，這邊只示範回傳
            return `Code diff for review:\n${diff.slice(0, 1000)}...`

        env:
          DIFF: ${{ steps.get_diff.outputs.diff }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Post review comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Automated Code Review by GPT
            ```
            ${{ steps.gpt_review.outputs.result }}
            ```
